### ISSUE TITLE
Visualize

### ISSUE THREAD

**Issue by farhanchaudhry54** [gedcom/scCCESS#1]
What is the best way to visualize the clusters?

**Comment by gedcom** [comment]
The final clusters are comparable to that of other discrete, non-hierarchical clustering methods (e.g. k-means), so you can visualise them as you would visualise the outputs of those methods such as colouring a t-sne plot by cluster.

**Comment by farhanchaudhry54** [comment]
Thank you got it to work

**Comment by db-beep** [comment]
How to visualize clustering results

**Comment by gedcom** [comment]
Hi db-beep, sorry for the delay. As I commented above, you can visualise the clustering results by applying a dimension-reduction method such as t-sne to the original data and colour by cluster.
